### ISSUE TITLE
Issue with migration commands

### ISSUE THREAD

**Issue by charleschen** [hellysmile/django-redis-sessions-fork#9]
there's an issue with the command for migration if there's a lot of Session data and there's are Session close to expiration.

For example if a certain Session expires in 5 seconds before the command is ran, and then the migration runs for 20 seconds and hits this Session, the expire_in becomes 15 seconds:

```python
expire_in = session.expire_date - now
expire_in = expire_in.seconds + expire_in.days * 86400
```

it shouldn't be 15 seconds, in fact the Session should just be ignored.  I caught this error since you can't set expiration time 0 and I had a Session that expired right when the code hit it.

**Comment by hellysmile** [comment]
Hmm, makes sense to move ```now``` declaration inside cycle... Any pull request for this?

**Comment by hellysmile** [comment]
resolved, pushing soon
